---
title: ""
author: ""
output: 
  pdf_document:
    latex_engine: xelatex
    toc: false
    toc_depth: 2
    number_sections: true
    keep_tex: true
fontsize: 11pt
geometry: margin=2.5cm
classoption: oneside
link-citations: yes
citation_package: natbib
---
\begin{titlepage}
\centering
\vspace*{5cm}

{\LARGE SY19 - Rapport de projet \par}
\vspace{1cm}
{\large Engel CALON, Bastien CUVILLIER, Camille MILON \par}
\vspace{0.5cm}
Université de Technologie de Compiègne \par
\vspace{2cm}
30 novembre 2025 \par

\end{titlepage}

# Introduction

A COMPLETER : très courte introduction car pas beaucoup de pages

# Régression

## Analyse descriptive

A COMPLETER

## Sélection de variables

A COMPLETER

## Transformations

A COMPLETER : parler ici des transformations appliquées sur les variables => si aucune, il faudra supprimer la section

## Régresseur

A COMPLETER : parler ici du régresseur choisi, expliquer pourquoi c'est le plus approprié par rapport aux autres

## Résultats et interprétation

A COMPLETER : Présenter les différents résultats et conclure


# Classification

## Analyse descriptive

A COMPLETER

## Sélection de variables

A COMPLETER

## Transformations

A COMPLETER : parler ici des transformations appliquées sur les variables => si aucune, il faudra supprimer la section

## Classifieur

A COMPLETER : parler ici du régresseur choisi, expliquer pourquoi c'est le plus approprié par rapport aux autres

## Résultats et interprétation

A COMPLETER : Présenter les différents résultats et conclure


# Jeu de données réel

## Présentation du jeu de données

A COMPLETER : description (origine du jeu de données, contexte, variables, classification binaire), objectif (problématique)

## Analyse descriptive

A COMPLETER

## Sélection de variables

A COMPLETER

## Transformations

A COMPLETER : parler ici des transformations appliquées sur les variables => si aucune, il faudra supprimer la section

## Classifieur

A COMPLETER : parler ici du régresseur choisi, expliquer pourquoi c'est le plus approprié par rapport aux autres

## Résultats et interprétation

A COMPLETER : Présenter les différents résultats et conclure